# API Services

version: '3.7'

services:

  auth:
    image: fonoster/fonos-auth
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=internal,websecure"
      - "traefik.http.routers.auth.rule=PathPrefix(`/fonos.auth.v1alpha1`)"
      - "traefik.http.services.auth.loadbalancer.server.scheme=h2c"
    volumes:
      - ${CONFIG}/rbac.json:/home/fonos/rbac.json

  agents:
    image: fonoster/fonos-agents
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agents.entrypoints=internal,websecure"
      - "traefik.http.routers.agents.rule=PathPrefix(`/fonos.agents.v1alpha1`)"
      - "traefik.http.services.agents.loadbalancer.server.scheme=h2c"
  
  domains:
    image: fonoster/fonos-domains
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.domains.entrypoints=internal,websecure"
      - "traefik.http.routers.domains.rule=PathPrefix(`/fonos.domains.v1alpha1`)"
      - "traefik.http.services.domains.loadbalancer.server.scheme=h2c"
  
  numbers:
    image: fonoster/fonos-numbers
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.numbers.entrypoints=internal,websecure" 
      - "traefik.http.routers.numbers.rule=PathPrefix(`/fonos.numbers.v1alpha1`)"
      - "traefik.http.services.numbers.loadbalancer.server.scheme=h2c"

  providers:
    image: fonoster/fonos-providers
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.providers.entrypoints=internal,websecure"    
      - "traefik.http.routers.providers.rule=PathPrefix(`/fonos.providers.v1alpha1`)"
      - "traefik.http.services.providers.loadbalancer.server.scheme=h2c"

  storage:
    image: fonoster/fonos-storage
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storage.entrypoints=internal,websecure"    
      - "traefik.http.routers.storage.rule=PathPrefix(`/fonos.storage.v1alpha1`)"
      - "traefik.http.services.storage.loadbalancer.server.scheme=h2c"
  
  callmanager:
    image: fonoster/fonos-callmanager
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.callmanager.entrypoints=internal,websecure"    
      - "traefik.http.routers.callmanager.rule=PathPrefix(`/fonos.callmanager.v1alpha1`)"
      - "traefik.http.services.callmanager.loadbalancer.server.scheme=h2c"

  appmanager:
    image: fonoster/fonos-appmanager
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appmanager.entrypoints=internal,websecure"    
      - "traefik.http.routers.appmanager.rule=PathPrefix(`/fonos.appmanager.v1alpha1`)"
      - "traefik.http.services.appmanager.loadbalancer.server.scheme=h2c"