version: '3.7'

services:

  sipproxy:
    image: ${SIPPROXY_IMAGE}
    restart: ${RESTART_POLICY}
    environment:
      EXTERN_ADDR: ${HOST_ADDR}
      DATA_SOURCE_PROVIDER: redis_data_provider
      DATA_SOURCE_PARAMETERS: host=${DS_HOST},port=${DS_PORT},secret=${DS_SECRET}
      BIND_ADDR: 0.0.0.0
      RECORD_ROUTE: 'true'
      REGISTRAR_INTF: Internal
    ports:
      - ${SIPPROXY_SIP_PORT}:${SIPPROXY_SIP_PORT}
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${SIPPROXY_API_PORT} || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.apiserver
    networks:
      fonos:
        aliases:
          - ${SIPPROXY_HOST}
    volumes:
      - ${CONFIG}/log4j2.yml:/opt/routr/config/log4j2.yml

  mediaserver:
    image: ${MS_IMAGE}
    restart: ${RESTART_POLICY}
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "${MS_ARI_USERNAME}:${MS_ARI_SECRET}", "http://localhost:8088/ari/asterisk/info"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      EXTERN_ADDR: ${HOST_ADDR}
      EXTERN_PORT: ${MS_SIP_PORT}
      # Warning: Temporal value
      AGI_URL: agi://${MC_HOST_PUBLIC}:${MC_AGI_PORT}
      SIPPROXY_HOST: ${HOST_ADDR}:${SIPPROXY_SIP_PORT}
      SIPPROXY_USERNAME: ${SIPPROXY_USERNAME}
      SIPPROXY_SECRET: ${SIPPROXY_SECRET}
      # Give asterisk a fake localnet to force it to always advertise its public address
      LOCALNET: '8.8.8.8'
    volumes:
      - data1-1:/home/fonos
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.mediaserver
    # This doesn't work on osx 
    # see: https://github.com/docker/for-mac/issues/1031
    network_mode: "host"

  mediacontroller:
    image: ${MC_IMAGE}
    restart: ${RESTART_POLICY}
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      APISERVER_ENDPOINT: ${AS_HOST}:{AS_PORT}
      EVENTS_BROKERS: amqp://${EB_USERNAME}:${EB_SECRET}@${EB_HOST}:${EB_PORT}
      # Warning: Hardcoded value
      EVENTS_QUEUE: apiserver
      TTS_ENGINE_HOST: ${TTS_ENGINE_HOST}
      TTS_ENGINE_PORT: ${TTS_ENGINE_PORT}
      LOGS_DRIVER_HOST: ${LOGS_DRIVER_HOST}
      LOGS_DRIVER_PORT: ${LOGS_DRIVER_PORT}
      LOG_OPT_TAG_PREFIX: ${LOG_OPT_TAG_PREFIX}
    volumes:
      - ${CONFIG}/config:/home/fonos/.fonos/config
      - data1-1:/home/fonos
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.mediacontroller
    networks:
      fonos:
        aliases:
          - ${MC_HOST}
