# Optional Secrets service (Vault)

version: '3.7'

networks:
  fonos:

services:

  secrets:
    image: ${SECRETS_IMAGE}
    entrypoint: vault server -config=/vault/config/vault.json   
    # ports:
      # - "127.0.0.1:8200:8200"
    volumes:
      - ${CONFIG}/file:/vault/file:rw
      - ${CONFIG}/vault.json:/vault/config/vault.json:rw
    cap_add:
      - IPC_LOCK
    networks:
      fonos:
        aliases: 
          - ${LOGS_DRIVER_HOST}      

  secrets_api:
    image: fonoster/fonos-secrets
    extends:
      file: api-common.yml
      service: common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secrets.entrypoints=internal,websecure"
      - "traefik.http.routers.secrets.rule=PathPrefix(`/fonos.secrets.v1alpha1`)"
      - "traefik.http.services.secrets.loadbalancer.server.scheme=h2c"
