# Optional TTS Engine (MaryTTS)

version: '3.7'

networks:
  fonos:

services:

  tts:
    image: ${TTS_IMAGE}
    restart: ${RESTART_POLICY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${TTS_ENGINE_PORT}"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - ${TTS_ENGINE_PORT}:${TTS_ENGINE_PORT}
    networks:
      fonos:
        aliases: 
          - ${TTS_ENGINE_HOST}
    logging:
      options:
        tag: ${LOG_OPT_TAG_PREFIX}.${COMPOSE_PROJECT_NAME}.tts
